name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every 24 hours
  workflow_dispatch:   # Allows you to trigger manually

jobs:
  tryhackme-badge-update:
    name: Update Badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KeizerSec/Tryhackme-Badge@main
        with:
          username: greenoff
